name: Python tests

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt black isort
      - name: Run isort
        run: isort --check .
      - name: Run black
        run: black --check .
      - name: Comment if linting failed
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :poop: Code linting failed, use `black` and `isort` to fix it.
