name: Python tests

on:
  pull_request:


jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt"
      - uses: psf/black@stable
      - name: Comment if linting failed
        if: failure()
        id: comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            :poop: Code linting failed, use `black` and `isort` to fix it.
      - name: Fail
        if: steps.comment.conclusion != 'failure' && steps.comment.conclusion != 'skipped'
        run: exit 1
  
